# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               BigEndian
tagline:             'Learn, love, loiter'
description:         'A journal of my thoughts.'
url:                 http://bigendian.io
baseurl:             'http://bigendian.io'
paginate:            5

# About/contact
author:
  name:              Qasim Javed
  url:               https://twitter.com/
  email:             jmisaq@gmail.com

# Custom vars
version:             1.0.0
